language: php
sudo: false
matrix:
  fast_finish: true
cache:
  directories:
    - vendor
    - bin
    - $HOME/.composer/cache
php:
- 5.6
- 7.0
before_script:
- composer install --prefer-dist
- mkdir -p build/logs
script:
- make lint
- make test
after_script:
- bin/coveralls -v